apiVersion: v1
kind: Pod 
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - image: mysql:5.6
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: wash123
      ports:
        - containerPort: 3306
